### ISSUE TITLE
Flutter Gradle Migration Problem

### ISSUE THREAD

**Issue by thisisdishang** [thisisdishang/HealthCare#4]
How to migrate flutter gradle in my old flutter project?

Below error occur
![Screenshot 2024-06-16 190244](https://github.com/thisisdishang/HealthCare/assets/91554337/db8bcf50-c3c7-4741-9e85-ffcf05bb73c7)

Project Link
https://github.com/thisisdishang/HealthCare

**Comment by Pratham-Makwana** [comment]
Issue resolved

**Comment by thisisdishang** [comment]
> Issue resolved

Okay Done
